module.exports = {
  ROLES: {
    CANDIDATE: "CANDIDATE",
    ADMIN: "ADMIN",
    SUPER_ADMIN: "SUPER_ADMIN",
  },

  APPLICATION_STATUS: {
    DRAFT: "DRAFT",
    SUBMITTED: "SUBMITTED",
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
  },

  DOCUMENT_TYPES: {
    CCCD: "CCCD",
    HOC_BA: "HOC_BA",
    DIEM_THI: "DIEM_THI",
    UU_TIEN: "UU_TIEN",
    ANH_3X4: "ANH_3X4",
  },
};
